import { useEffect, useMemo, useState } from 'react';
import { BellRing, CalendarDays, Edit3, Plus, Users, X } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useAuth } from '../contexts/AuthContext';

type Interest = { id: string; name: string; description?: string; interest_start_date: string; interest_end_date?: string; program_start_date: string; status: 'active'|'inactive'; color: string; inquiry_interests?: Array<{ id:string; last_follow_up_at?:string; status:string; inquiries?:{customer_name:string;phone:string;employees?:{name:string}} }> };
const empty: {name:string;description:string;interest_start_date:string;interest_end_date:string;program_start_date:string;status:'active'|'inactive';color:string} = { name:'', description:'', interest_start_date:'', interest_end_date:'', program_start_date:'', status:'active', color:'#D4A017' };

export default function Interests() {
  const { profile } = useAuth();
  const isAdmin = ['super_admin','مالك النظام','مدير النظام'].includes(profile?.role || '');
  const [items,setItems] = useState<Interest[]>([]); const [editing,setEditing] = useState<Interest|null>(null);
  const [form,setForm] = useState(empty); const [open,setOpen] = useState(false); const [loading,setLoading] = useState(true);
  const load = async()=>{ setLoading(true); const {data}=await supabase.from('interests').select('*, inquiry_interests(id,last_follow_up_at,status,inquiries(customer_name,phone,employees(name)))').order('program_start_date'); setItems((data as Interest[])||[]); setLoading(false); };
  useEffect(()=>{load();},[]);
  const save=async(e:React.FormEvent)=>{e.preventDefault(); const payload={...form,interest_end_date:form.interest_end_date||null,created_by:profile?.id}; if(editing) await supabase.from('interests').update(payload).eq('id',editing.id); else await supabase.from('interests').insert(payload); setOpen(false);setEditing(null);setForm(empty);load();};
  const edit=(i:Interest)=>{setEditing(i);setForm({name:i.name,description:i.description||'',interest_start_date:i.interest_start_date,interest_end_date:i.interest_end_date||'',program_start_date:i.program_start_date,status:i.status,color:i.color});setOpen(true)};
  const alerts=useMemo(()=>items.filter(i=>{const d=Math.ceil((new Date(i.program_start_date).getTime()-Date.now())/86400000);return d<=15&&(i.inquiry_interests||[]).some(x=>!x.last_follow_up_at)}),[items]);
  return <div className="space-y-6" dir="rtl">
    <div className="flex items-center justify-between"><div><h1 className="section-title">الاهتمامات</h1><p className="section-subtitle">البرامج الموسمية واهتمامات العملاء والتنبيهات المرتبطة بها</p></div>{isAdmin&&<button className="btn-gold" onClick={()=>{setEditing(null);setForm(empty);setOpen(true)}}><Plus size={16}/> اهتمام جديد</button>}</div>
    {alerts.length>0&&<div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><h3 className="font-bold text-amber-900 flex gap-2 items-center"><BellRing size={18}/>تنبيهات المتابعة ({alerts.length})</h3><div className="grid md:grid-cols-2 gap-3 mt-3">{alerts.map(i=>{const links=i.inquiry_interests||[];const pending=links.filter(x=>!x.last_follow_up_at);return <div key={i.id} className="bg-white rounded-xl p-3 border border-amber-100"><b>{i.name}</b><p className="text-xs text-gray-600 mt-1">{links.length} عميل · {pending.length} لم تتم متابعتهم · يبدأ {new Date(i.program_start_date).toLocaleDateString('ar-EG')}</p></div>})}</div></div>}
    {loading?<div className="text-center py-16">جارٍ التحميل...</div>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{items.map(i=>{const links=i.inquiry_interests||[];const contacted=links.filter(x=>x.last_follow_up_at).length;return <div key={i.id} className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden"><div className="h-2" style={{background:i.color}}/><div className="p-5"><div className="flex justify-between"><div><h3 className="font-bold text-navy-900">{i.name}</h3><span className={`text-xs ${i.status==='active'?'text-emerald-600':'text-gray-400'}`}>{i.status==='active'?'نشط':'غير نشط'}</span></div>{isAdmin&&<button onClick={()=>edit(i)} className="p-2 text-gray-500"><Edit3 size={16}/></button>}</div><p className="text-sm text-gray-500 mt-3 min-h-10">{i.description||'لا يوجد وصف'}</p><div className="mt-4 space-y-2 text-sm"><p className="flex gap-2"><CalendarDays size={15} style={{color:i.color}}/>موعد البرنامج: {new Date(i.program_start_date).toLocaleDateString('ar-EG')}</p><p className="flex gap-2"><Users size={15} style={{color:i.color}}/>{links.length} عميل · {contacted} تمت متابعتهم · {links.length-contacted} بانتظار المتابعة</p></div></div></div>})}</div>}
    {open&&<div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4"><form onSubmit={save} className="bg-white rounded-2xl p-6 w-full max-w-lg space-y-4"><div className="flex justify-between"><h2 className="font-bold text-lg">{editing?'تعديل الاهتمام':'إضافة اهتمام'}</h2><button type="button" onClick={()=>setOpen(false)}><X/></button></div><input required className="form-input" placeholder="اسم الاهتمام" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><textarea className="form-input" placeholder="وصف مختصر" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="grid grid-cols-2 gap-3"><label className="text-xs">بداية فترة الاهتمام<input required type="date" className="form-input mt-1" value={form.interest_start_date} onChange={e=>setForm({...form,interest_start_date:e.target.value})}/></label><label className="text-xs">نهاية الفترة<input type="date" className="form-input mt-1" value={form.interest_end_date} onChange={e=>setForm({...form,interest_end_date:e.target.value})}/></label></div><label className="text-xs">بداية البرنامج<input required type="date" className="form-input mt-1" value={form.program_start_date} onChange={e=>setForm({...form,program_start_date:e.target.value})}/></label><div className="grid grid-cols-2 gap-3"><select className="form-input" value={form.status} onChange={e=>setForm({...form,status:e.target.value as 'active'|'inactive'})}><option value="active">نشط</option><option value="inactive">غير نشط</option></select><input type="color" className="form-input h-11" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></div><button className="btn-gold w-full justify-center">حفظ</button></form></div>}
  </div>;
}
