-- ===== ALTER TABLE CUSTOMERS =====
ALTER TABLE customers
ADD COLUMN IF NOT EXISTS client_type TEXT DEFAULT 'فردي' CHECK (client_type IN ('فردي', 'فوج')),
ADD COLUMN IF NOT EXISTS parent_customer_id UUID REFERENCES customers(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS age_group TEXT DEFAULT 'بالغ' CHECK (age_group IN ('بالغ', 'طفل', 'رضيع'));

-- ===== ALTER TABLE PACKAGES =====
ALTER TABLE packages
ADD COLUMN IF NOT EXISTS price_double NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS price_triple NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS price_quad NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS price_child NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS price_infant NUMERIC DEFAULT 0;
